LU factorization

In [6]:
import numpy as np
from scipy.linalg import lu
import sympy

# Create a matrix
A = np.array([[2, 4, -1, 5, -2], [-4, -5, 3, -8, 1], [2, -5, -4, 1, 8], [-6, 0, 7, -3, 1]])

# # Perform LU factorization
P, Lower, Upper = lu(A)

# Convert to a SymPy matrix
A_sym = sympy.Matrix(A)

# Perform LU factorization
L, U, _ = A_sym.LUdecomposition()

print(A)


print("L:")
print(np.array(L))
print("U:")
print(np.array(U))

print("The scipy.linalg library")
print()

print(Lower)
print(Upper)

[[ 2  4 -1  5 -2]
 [-4 -5  3 -8  1]
 [ 2 -5 -4  1  8]
 [-6  0  7 -3  1]]
L:
[[1 0 0 0]
 [-2 1 0 0]
 [1 -3 1 0]
 [-3 4 2 1]]
U:
[[2 4 -1 5 -2]
 [0 3 1 2 -3]
 [0 0 0 2 1]
 [0 0 0 0 5]]
The scipy.linalg library

[[ 1.          0.          0.          0.        ]
 [ 0.66666667  1.          0.          0.        ]
 [-0.33333333  1.          1.          0.        ]
 [-0.33333333 -0.8        -0.          1.        ]]
[[-6.00000000e+00  0.00000000e+00  7.00000000e+00 -3.00000000e+00
   1.00000000e+00]
 [ 0.00000000e+00 -5.00000000e+00 -1.66666667e+00 -6.00000000e+00
   3.33333333e-01]
 [ 0.00000000e+00  0.00000000e+00 -8.88178420e-16  6.00000000e+00
   8.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 -8.00000000e-01
  -1.40000000e+00]]


It seems that the sympy library gives more accurate solutions